### ISSUE TITLE
Enable by default

### ISSUE THREAD

**Issue by bbrks** [taggon/livereload#11]
Just wondering how easy it would be to have an option to enable livereload by default?

I've tried messing with my init.coffee, but don't know enough about Atom's structure to try and achieve this yet!

**Comment by taggon** [comment]
Put the following script into your `init.coffee`:
```coffee
workspaceView = atom.views.getView atom.workspace
atom.commands.dispatch workspaceView, 'livereload:toggle'
```

**Comment by bbrks** [comment]
Cool! Thank you very much. :+1:
