### ISSUE TITLE
Use the `atom-workspace` tag instead of the `workspace` class.

### ISSUE THREAD

**Issue by rhc-lconrad** [taggon/livereload#13]
Reported on install; OSX, Atom Version 0.201.0 (0.201.0)
In keymaps/livereload.cson: Use the `atom-workspace` tag instead of the `workspace` class.

**Comment by awakekat** [comment]
Ditto... Sharing Deprecation warning from Atom

**Comment by taggon** [comment]
4d09367488bdb1c7eb312a89e6034fa89c0c031d Fixed.
