### ISSUE TITLE
Package.activateResources is deprecated.

### ISSUE THREAD

**Issue by rhc-lconrad** [taggon/livereload#14]
Reported on install; OSX, Atom Version 0.201.0 (0.201.0)
The context menu CSON format has changed. Please see
https://atom.io/docs/api/latest/ContextMenuManager

**Comment by jobnomade** [comment]
The context menu CSON format has changed. Please see https://atom.io/docs/api/latest/ContextMenuManager#context-menu-cson-format for more info.
Report Issue
Ubuntu 14.04. LTS, 64 Bit, Atom Version 0.204.0

**Comment by taggon** [comment]
From v0.3.0, livereload package does not support context menu.
Use it via main menu.

Thanks.
