### ISSUE TITLE
it does not work with Chrome LiveReload extension

### ISSUE THREAD

**Issue by CaxPlus** [taggon/livereload#17]
I'm based on your steps, and finally found no effect,but livereload isconnectted

**Comment by taggon** [comment]
@CaxPlus Could you tell me what you did step by step?

**Comment by tujoworker** [comment]
@CaxPlus I thing he is referring to https://chrome.google.com/webstore/detail/livereload/jnihajbhpnppcggbcgedagnkighmdlei - but this one need an app you have to pay, and is not affiliated with your cool server solution.

**Comment by tujoworker** [comment]
For me it works fine. But the extension is not showing the connected status that good visually.

**Comment by daslicht** [comment]
works fine here

**Comment by taggon** [comment]
@CaxPlus I'm closing this issue. If you still have the same problem let me know it, but this time tell me your user environment too.
