### ISSUE TITLE
Feature Request: Delay

### ISSUE THREAD

**Issue by egyptianbman** [taggon/livereload#22]
Thanks for the awesome plugin.  If possible, can you add an option to set the number of seconds or milliseconds delay after saving, before triggering a reload?

**Comment by taggon** [comment]
Good idea! I'll consider it for the next release.

**Comment by egyptianbman** [comment]
Thanks!

**Comment by eliezedeck** [comment]
+1 for this. This is quite an important feature since I usually also trigger an express server reload, which takes about 600 milliseconds to come back up.

Right now, the page gets a connection error because the server is not yet online at the time the reload has been triggered.

**Comment by taggon** [comment]
Update to v0.4.3 :)
