### ISSUE TITLE
Slow on typing code - how do I exclude this files

### ISSUE THREAD

**Issue by tujoworker** [taggon/livereload#24]
Hi,

thanks for making this cool livereload for Atom.
You suggest to exclude directories which have many files such as node_modules.

How do I exclude this files? Or is not that the reason when typing gets really slow once the server is enabled?

**Comment by tujoworker** [comment]
ok, looks like I have to enter the folders in the Additional Exclusions in the Settings. Anyway, this takes no effect for now. Do I have only to enter a foldername + slash?

Also, I think you are using the "Project Folders" for checking for changes. Is that right?

**Comment by tujoworker** [comment]
ahh, OK. Thees kind of changes need a Atom restart. Right? Works for me at least.

**Comment by taggon** [comment]
Actually just restarting the extension would work. It loads its configuration whenever the server starts.
And yes. It currently watches Project Folders as default. I'll add new feature let users to set the root folder.

**Comment by tujoworker** [comment]
Sounds good :)

--
This email was sent on the road.
