### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by LasseRafn** [taggon/livereload#3]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
LivereloadView.initialize (/Users/lasserafn/.atom/packages/livereload/lib/livereload-view.coffee:16:9)
```

**Comment by taggon** [comment]
4d09367488bdb1c7eb312a89e6034fa89c0c031d Fixed.
